version: '3.8'

services:
  web:
    build: .
    command: poetry run python -m core.manage runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: project
      POSTGRES_USER: project
      POSTGRES_PASSWORD: projectpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
